# This is a basic workflow to help you get started with Actions

name: CI, Deploy Credit Card Payment NgRx in FireBase

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
#    - release/*
#   branches: [ master ]
# pull_request:
#  branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firebase-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          #        node-version: '14.15.1'
          node-version: "14.x"
      - run: npm install
      #    - run: npm run build:prod
      #    - run: npm run build --prod
      - run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          #        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_TOKEN: "1//09YiaqS7MtKHjCgYIARAAGAkSNwF-L9IrdvHACuuGfRV7tIQmWbsrt4vSoyKtAOCJZCS_3W1VDMIxgW09-2Lnd-3y18FUhCbOYOI"
